apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    type: frontend
spec:
  selector:
    matchLabels:
      type: frontend
  replicas: 4
  template:
    metadata:
      name: nginx-2
      labels:
        type: frontend
    spec:
      containers:
        - name: nginx-2
          image: nginx:1.7.1